/* eslint-disable */
// 本文件由 dist 编译产物重建（服务器上原 src 目录已丢失）。
// 原始路径: src/db/seed.ts

export { seedResources } from './resourceSeed';
export { seedCertificates } from './certificateSeed';
export { seedCompetitionStages } from './stagesSeed';

// ===== 类型定义（自 .d.ts 还原）=====
import type { DatabaseWrapper } from './database';
interface CompetitionSeed {
    name: string;
    category: string;
    description: string;
    target_audience: string;
    fee: string;
    format: 'team' | 'individual';
    reg_start_month: number;
    reg_end_month: number | null;
    requirements: string;
    official_website?: string;
    past_papers_url?: string;
}

export const competitions = [
    // 综合类 (7)
    { name: '中国国际大学生创新大赛', category: '综合类', description: '原中国国际"互联网+"大学生创新创业大赛，鼓励大学生创新创业', target_audience: '全日制本科生、研究生（含博士）及毕业5年内的创业者', fee: '免费', format: 'team', reg_start_month: 4, reg_end_month: 7, requirements: '每个项目团队成员不少于3人\n需有1-2名指导教师\n项目需具有创新性和商业价值\n需提交商业计划书和项目展示材料\n作品须为原创，不得侵犯他人知识产权', official_website: 'https://cy.ncss.cn/', past_papers_url: 'https://cy.ncss.cn/information/index' },
    { name: '"挑战杯"全国大学生课外学术科技作品竞赛', category: '综合类', description: '被誉为中国大学生科技创新的"奥林匹克"', target_audience: '全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 1, reg_end_month: 5, requirements: '每件作品可由不超过5人组成团队\n需有1-2名指导教师\n作品分为自然科学类学术论文、哲学社会科学类社会调查报告和学术论文、科技发明制作三大类\n作品须为学生课外学术科技或社会实践活动成果\n毕业设计和课程设计不在申报范围内', official_website: 'https://www.tiaozhanbei.net/', past_papers_url: 'https://www.tiaozhanbei.net/project/' },
    { name: '"挑战杯"中国大学生创业计划竞赛', category: '综合类', description: '大学生创业计划竞赛，培养创业意识和能力', target_audience: '全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 3, reg_end_month: 6, requirements: '每个团队3-15人\n需有1-2名指导教师\n分为科技创新和未来产业、乡村振兴和农业农村现代化、社会治理和公共服务、文化创意和区域合作等组别\n需提交完整的创业计划书\n项目须具有可行性和创新性', official_website: 'https://www.tiaozhanbei.net/', past_papers_url: 'https://www.tiaozhanbei.net/project/' },
    { name: '全国大学生数学建模竞赛', category: '综合类', description: '运用数学方法和计算机技术解决实际问题', target_audience: '全日制本科生及研究生（本科组和研究生组分开竞赛）', fee: '免费', format: 'team', reg_start_month: 6, reg_end_month: 9, requirements: '每队3人，专业不限\n竞赛期间不得与队外任何人讨论赛题\n比赛时间为连续72小时\n需提交论文形式的解答报告\n可使用任何参考资料、计算机和软件', official_website: 'http://www.mcm.edu.cn/', past_papers_url: 'http://www.mcm.edu.cn/html_cn/block/8a76c4d85fa0d468015fdb3c4f7c0012.html' },
    { name: '全国大学生节能减排社会实践与科技竞赛', category: '综合类', description: '以节能减排为主题的科技创新竞赛', target_audience: '全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 3, reg_end_month: 7, requirements: '每个团队不超过7人\n需有1-3名指导教师\n作品须围绕节能减排主题\n分为科技作品类和社会实践调查报告类\n科技作品需提交实物或模型及技术报告\n社会实践类需提交调查报告', official_website: 'http://www.jienengjianpai.org/', past_papers_url: 'http://www.jienengjianpai.org/works.html' },
    { name: '全国大学生创新创业训练计划年会展示', category: '综合类', description: '展示大学生创新创业训练计划项目成果', target_audience: '承担国家级大学生创新创业训练计划项目的全日制本科生', fee: '免费', format: 'team', reg_start_month: 5, reg_end_month: 10, requirements: '须为国家级大创计划立项项目团队\n每个项目团队3-5人\n需有1-2名指导教师\n需提交项目研究成果报告\n分为学术论文展示、创新创业实践展示等环节', official_website: 'https://gjcxcy.bjtu.edu.cn/', past_papers_url: 'https://gjcxcy.bjtu.edu.cn/Index/ItemList' },
    { name: '世界大学生桥梁设计大赛', category: '综合类', description: '桥梁结构设计与创新竞赛', target_audience: '土木工程、桥梁工程、结构工程等相关专业全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 3, reg_end_month: 8, requirements: '每队2-5人\n需有1名指导教师\n需提交桥梁设计方案和结构模型\n模型需满足承载力和美观性要求\n设计方案需包含计算书和设计图纸' },
    // 计算机类 (10)
    { name: '中国大学生计算机设计大赛', category: '计算机类', description: '计算机应用设计与开发竞赛', target_audience: '全日制本科生（含高职）', fee: '免费', format: 'team', reg_start_month: 1, reg_end_month: 5, requirements: '每队1-5人\n需有1-2名指导教师\n分为软件应用与开发、微课与教学辅助、物联网应用、大数据应用、人工智能应用、信息可视化设计等类别\n作品须为原创\n需提交作品源代码、设计文档和演示视频', official_website: 'http://jsjds.blcu.edu.cn/', past_papers_url: 'http://jsjds.blcu.edu.cn/zphz/index.htm' },
    { name: 'ACM-ICPC国际大学生程序设计竞赛', category: '计算机类', description: '国际顶级程序设计竞赛', target_audience: '全日制本科生及研究生（每人最多参加2次世界总决赛）', fee: '免费', format: 'team', reg_start_month: 9, reg_end_month: 11, requirements: '每队3人，配1名教练\n同一学校可派多支队伍参赛\n比赛时使用1台电脑\n竞赛时长5小时，需解决8-13道算法题\n支持C/C++、Java、Python等编程语言\n以解题数量和用时排名', official_website: 'https://icpc.global/', past_papers_url: 'https://codeforces.com/gyms' },
    { name: '全国大学生信息安全竞赛', category: '计算机类', description: '信息安全技术与实践竞赛', target_audience: '全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 3, reg_end_month: 7, requirements: '分为作品赛和创新实践能力赛两个类别\n作品赛每队不超过4人，需1名指导教师\n创新实践能力赛（CTF）每队不超过4人\n作品赛需提交信息安全相关的软硬件作品\n创新实践能力赛考察密码学、逆向分析、漏洞挖掘等技能', official_website: 'http://www.ciscn.cn/', past_papers_url: 'https://ctf.bugku.com/' },
    { name: '全国大学生软件测试大赛', category: '计算机类', description: '软件测试技术与实践竞赛', target_audience: '计算机、软件工程等相关专业全日制本科生及研究生', fee: '免费', format: 'individual', reg_start_month: 3, reg_end_month: 6, requirements: '个人赛，独立完成\n分为功能测试和性能测试等赛项\n需掌握软件测试基本理论和方法\n比赛使用统一的测试平台和工具\n需在规定时间内完成测试用例设计和缺陷报告' },
    { name: '中国高校计算机大赛-团体程序设计天梯赛', category: '计算机类', description: '团体程序设计能力竞赛', target_audience: '全日制本科生及高职学生', fee: '免费', format: 'team', reg_start_month: 1, reg_end_month: 4, requirements: '以学校为单位组队，每队10人\n比赛时长3小时\n题目分为基础级、进阶级和登顶级三个难度\n使用C/C++、Java或Python编程\n以团队总分排名', official_website: 'https://gplt.patest.cn/', past_papers_url: 'https://pintia.cn/problem-sets?tab=1' },
    { name: '中国高校计算机大赛-大数据挑战赛', category: '计算机类', description: '大数据分析与应用竞赛', target_audience: '全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 3, reg_end_month: 8, requirements: '每队1-5人\n需有1名指导教师\n围绕大数据分析与应用的实际问题展开\n需提交数据分析报告和算法模型\n分为初赛（线上）和决赛（现场答辩）', official_website: 'https://www.saikr.com/', past_papers_url: 'https://tianchi.aliyun.com/competition/gameList/activeList' },
    { name: '中国高校计算机大赛-网络技术挑战赛', category: '计算机类', description: '网络技术应用与创新竞赛', target_audience: '全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 4, reg_end_month: 9, requirements: '每队3人\n需有1名指导教师\n分为创新创业类和技术挑战类\n创新创业类需提交网络技术相关作品\n技术挑战类考察网络规划、配置和故障排除能力' },
    { name: '中国高校计算机大赛-人工智能创意赛', category: '计算机类', description: '人工智能技术创新应用竞赛', target_audience: '全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 3, reg_end_month: 8, requirements: '每队1-5人\n需有1名指导教师\n作品须基于人工智能技术\n需提交作品演示视频、技术文档和源代码\n分为命题赛道和自由赛道', official_website: 'https://aicontest.baidu.com/', past_papers_url: 'https://aistudio.baidu.com/competition' },
    { name: '中国高校计算机大赛-移动应用创新赛', category: '计算机类', description: '移动应用开发与创新竞赛', target_audience: '全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 4, reg_end_month: 9, requirements: '每队1-5人\n需有1名指导教师\n作品须为移动平台应用（iOS/Android/HarmonyOS）\n需提交应用安装包、源代码和设计文档\n应用须具有创新性和实用价值' },
    { name: '全国大学生物联网设计竞赛', category: '计算机类', description: '物联网系统设计与应用竞赛', target_audience: '全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 3, reg_end_month: 8, requirements: '每队不超过4人\n需有1名指导教师\n作品须包含物联网感知层、网络层和应用层\n需提交实物作品和技术报告\n作品需现场演示和答辩', official_website: 'http://iot.sjtu.edu.cn/', past_papers_url: 'http://iot.sjtu.edu.cn/show.aspx?info_lb=36&flag=2' },
    // 电子信息类 (10)
    { name: '全国大学生电子设计竞赛', category: '电子信息类', description: '电子系统设计与制作竞赛', target_audience: '全日制本科生及高职学生', fee: '免费', format: 'team', reg_start_month: 5, reg_end_month: 8, requirements: '每队3人，专业不限\n需有1名指导教师\n竞赛时间为连续4天3夜\n需完成电子系统的设计、制作和调试\n分为仪器仪表类、电力电子类、信号处理类等多个方向\n需提交设计报告和实物作品', official_website: 'http://nuedc.xjtu.edu.cn/', past_papers_url: 'http://nuedc.xjtu.edu.cn/Item/list.asp?id=1003' },
    { name: '全国大学生智能汽车竞赛', category: '电子信息类', description: '智能车设计与制作竞赛', target_audience: '全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 1, reg_end_month: 7, requirements: '每队2-3人\n需有1名指导教师\n需设计制作能自主识别道路的智能车\n分为摄像头组、电磁组、创意组等多个组别\n需提交技术报告\n智能车须在规定赛道上完成比赛', official_website: 'https://smartcar.cdstm.cn/', past_papers_url: 'https://smartcar.cdstm.cn/index/article/index.html?cid=7' },
    { name: '全国大学生嵌入式芯片与系统设计竞赛', category: '电子信息类', description: '嵌入式系统设计与开发竞赛', target_audience: '电子信息、计算机、自动化等相关专业全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 3, reg_end_month: 8, requirements: '每队2-3人\n需有1名指导教师\n基于指定嵌入式平台进行开发\n需完成系统设计、编程和调试\n需提交设计方案、源代码和技术报告\n作品需现场演示', official_website: 'https://www.socchina.net/', past_papers_url: 'https://www.socchina.net/works' },
    { name: '全国大学生FPGA创新设计竞赛', category: '电子信息类', description: 'FPGA技术创新应用竞赛', target_audience: '电子信息、通信工程、计算机等相关专业全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 4, reg_end_month: 9, requirements: '每队2-3人\n需有1名指导教师\n基于FPGA平台进行创新设计\n需提交设计方案和技术报告\n作品须具有创新性和实用价值\n需进行现场演示和答辩' },
    { name: '全国大学生集成电路创新创业大赛', category: '电子信息类', description: '集成电路设计与创新竞赛', target_audience: '全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 3, reg_end_month: 8, requirements: '每队1-5人\n需有1名指导教师\n分为芯片设计、EDA工具应用、嵌入式系统等赛道\n需提交设计方案和仿真验证结果\n决赛需现场答辩\n鼓励使用国产EDA工具和芯片平台', official_website: 'https://univ.ciciec.com/', past_papers_url: 'https://univ.ciciec.com/works' },
    { name: '全国大学生光电设计竞赛', category: '电子信息类', description: '光电技术设计与应用竞赛', target_audience: '光电信息、光学工程、电子科学等相关专业全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 4, reg_end_month: 8, requirements: '每队不超过3人\n需有1名指导教师\n分为理论设计和实验作品两大类\n需提交设计报告或实验报告\n实验作品需现场演示\n作品须体现光电技术的创新应用' },
    { name: '中国大学生电脑鼠走迷宫竞赛', category: '电子信息类', description: '电脑鼠智能控制竞赛', target_audience: '全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 5, reg_end_month: 10, requirements: '每队1-3人\n需有1名指导教师\n需设计制作能自主走迷宫的电脑鼠\n电脑鼠须满足尺寸和重量限制\n分为电脑鼠竞速赛和创意赛\n以完成迷宫的时间排名' },
    { name: '全国大学生通信专题设计竞赛', category: '电子信息类', description: '通信系统设计与实现竞赛', target_audience: '通信工程、电子信息工程、信息工程等相关专业全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 4, reg_end_month: 9, requirements: '每队不超过3人\n需有1名指导教师\n围绕通信技术热点问题进行设计\n需提交设计方案和技术报告\n作品需现场演示和答辩\n鼓励使用5G、物联网等新技术' },
    { name: '睿抗机器人开发者大赛', category: '电子信息类', description: '机器人开发与应用竞赛', target_audience: '全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 3, reg_end_month: 8, requirements: '每队2-5人\n需有1名指导教师\n分为RAICOM智能机器人、机器人创意设计等赛项\n需完成机器人的设计、编程和调试\n需提交技术报告和演示视频\n决赛需现场操作演示', official_website: 'https://www.raicom.com.cn/', past_papers_url: 'https://www.raicom.com.cn/works' },
    { name: '全国大学生电子商务"创新、创意及创业"挑战赛', category: '电子信息类', description: '电子商务创新创业竞赛', target_audience: '全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 3, reg_end_month: 7, requirements: '每队3-5人\n需有1-2名指导教师\n围绕电子商务创新创业主题\n需提交商业计划书和项目展示材料\n分为创新类、创意类和创业类三个赛道\n决赛需现场路演答辩', official_website: 'http://www.3chuang.net/', past_papers_url: 'http://www.3chuang.net/works' },
    // 其他工学类 (10)
    { name: '全国大学生机械创新设计大赛', category: '其他工学类', description: '机械产品创新设计竞赛', target_audience: '机械工程、机械设计制造及其自动化等相关专业全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 1, reg_end_month: 5, requirements: '每队3-5人\n需有1-2名指导教师\n作品须为机械类创新设计\n需提交实物模型或样机\n需提交设计说明书和图纸\n作品须能现场演示功能' },
    { name: '全国大学生工程训练综合能力竞赛', category: '其他工学类', description: '工程实践与创新能力竞赛', target_audience: '全日制本科生', fee: '免费', format: 'team', reg_start_month: 3, reg_end_month: 6, requirements: '每队3-5人\n需有1-2名指导教师\n分为工程基础、智能+、虚拟仿真等赛道\n需完成工程制作和现场操作\n考察工程实践能力和创新思维\n需提交技术报告' },
    { name: '全国大学生化工设计竞赛', category: '其他工学类', description: '化工过程设计与优化竞赛', target_audience: '化学工程与工艺、制药工程等相关专业全日制本科生', fee: '免费', format: 'team', reg_start_month: 2, reg_end_month: 8, requirements: '每队5人\n需有1-2名指导教师\n需完成化工过程的工艺设计\n需提交设计说明书、工艺流程图、设备图等\n需进行经济分析和安全评估\n决赛需现场答辩' },
    { name: '全国大学生金相技能大赛', category: '其他工学类', description: '金属材料金相分析技能竞赛', target_audience: '材料科学与工程、金属材料工程等相关专业全日制本科生', fee: '免费', format: 'individual', reg_start_month: 3, reg_end_month: 7, requirements: '个人赛，独立完成\n需在规定时间内完成金相试样的制备和观察\n考察磨制、抛光、腐蚀和显微观察等技能\n需正确识别金属组织\n评分包括试样质量和组织识别准确性' },
    { name: '全国大学生交通运输科技大赛', category: '其他工学类', description: '交通运输领域科技创新竞赛', target_audience: '交通运输、交通工程、物流工程等相关专业全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 1, reg_end_month: 5, requirements: '每队不超过5人\n需有1-2名指导教师\n围绕交通运输领域的科技创新\n分为交通规划、智能交通、运输管理等方向\n需提交科技论文或创新作品\n决赛需现场答辩' },
    { name: '全国大学生结构设计竞赛', category: '其他工学类', description: '结构模型设计与制作竞赛', target_audience: '土木工程、建筑工程等相关专业全日制本科生', fee: '免费', format: 'team', reg_start_month: 4, reg_end_month: 10, requirements: '每队3人\n需有1名指导教师\n需设计制作结构模型\n模型材料和尺寸有严格限制\n需进行加载试验\n以承载能力与自重比等指标评判' },
    { name: '全国大学生水利创新设计大赛', category: '其他工学类', description: '水利工程创新设计竞赛', target_audience: '水利水电工程、水文与水资源工程等相关专业全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 3, reg_end_month: 7, requirements: '每队3-5人\n需有1-2名指导教师\n围绕水利工程创新设计\n需提交设计方案和技术报告\n鼓励结合实际水利工程问题\n决赛需现场答辩和作品展示' },
    { name: '全国大学生先进成图技术与产品信息建模创新大赛', category: '其他工学类', description: '工程制图与建模技术竞赛', target_audience: '工科相关专业全日制本科生及研究生', fee: '免费', format: 'individual', reg_start_month: 3, reg_end_month: 7, requirements: '个人赛，独立完成\n分为机械类和建筑类两大方向\n考察手工绘图和计算机绘图能力\n需熟练使用CAD/BIM等软件\n比赛时间约4-6小时\n需在规定时间内完成图纸绘制' },
    { name: '全国大学生冶金科技竞赛', category: '其他工学类', description: '冶金技术创新竞赛', target_audience: '冶金工程、材料科学与工程等相关专业全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 4, reg_end_month: 8, requirements: '每队3-5人\n需有1名指导教师\n围绕冶金技术创新\n分为钢铁冶金、有色冶金等方向\n需提交科技论文或创新作品\n决赛需现场答辩' },
    { name: '全国大学生船舶能源与动力创新大赛', category: '其他工学类', description: '船舶能源与动力系统创新竞赛', target_audience: '船舶与海洋工程、轮机工程、能源与动力工程等相关专业全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 3, reg_end_month: 9, requirements: '每队3-5人\n需有1名指导教师\n围绕船舶能源与动力系统创新\n需提交设计方案和技术报告\n鼓励节能减排和新能源应用\n决赛需现场答辩和作品展示' },
    // 理学类 (8)
    { name: '全国大学生数学竞赛', category: '理学类', description: '数学基础理论与应用竞赛', target_audience: '全日制本科生（分数学专业组和非数学专业组）', fee: '免费', format: 'individual', reg_start_month: 9, reg_end_month: 10, requirements: '个人赛，独立完成\n分为数学专业组（数学类）和非数学专业组\n考试时间为2.5小时\n考察高等数学、数学分析、线性代数等知识\n初赛在各省举行，决赛为全国统一考试', official_website: 'http://www.cmathc.cn/', past_papers_url: 'http://www.cmathc.cn/list.php?fid=24' },
    { name: '全国大学生物理实验竞赛', category: '理学类', description: '物理实验技能与创新竞赛', target_audience: '全日制本科生', fee: '免费', format: 'individual', reg_start_month: 5, reg_end_month: 7, requirements: '个人赛或团队赛（视赛项而定）\n分为命题类实验和自选课题类实验\n命题类需在规定时间内完成指定实验\n自选课题类需提交实验报告和创新成果\n考察实验操作技能和数据分析能力', official_website: 'http://www.phylab.cn/', past_papers_url: 'http://www.phylab.cn/works' },
    { name: '全国大学生化学实验创新设计竞赛', category: '理学类', description: '化学实验创新设计竞赛', target_audience: '化学、应用化学、化学工程等相关专业全日制本科生', fee: '免费', format: 'team', reg_start_month: 3, reg_end_month: 7, requirements: '每队3人\n需有1名指导教师\n分为化学实验创新设计和化学实验教学设计两类\n需提交实验方案和实验报告\n实验须具有创新性和可操作性\n决赛需现场操作和答辩' },
    { name: '全国大学生生命科学竞赛', category: '理学类', description: '生命科学创新实验竞赛', target_audience: '生物科学、生物技术、生物工程等相关专业全日制本科生', fee: '免费', format: 'team', reg_start_month: 1, reg_end_month: 5, requirements: '每队3-5人\n需有1-2名指导教师\n分为创新实验和创业计划两个赛道\n创新实验需提交研究论文和实验报告\n创业计划需提交商业计划书\n决赛需现场答辩', official_website: 'http://culsc.cn/', past_papers_url: 'http://culsc.cn/works' },
    { name: '全国大学生统计建模大赛', category: '理学类', description: '统计方法与建模应用竞赛', target_audience: '全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 5, reg_end_month: 9, requirements: '每队3人\n需有1名指导教师\n围绕统计方法与实际应用\n需运用统计学方法分析实际数据\n需提交统计建模论文\n论文须包含数据来源、模型建立和结果分析' },
    { name: '全国大学生市场调查与分析大赛', category: '理学类', description: '市场调查分析方法与实践竞赛', target_audience: '全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 1, reg_end_month: 5, requirements: '每队3-5人\n需有1名指导教师\n需完成完整的市场调查项目\n需提交调查方案、问卷设计和分析报告\n需运用统计分析方法处理数据\n决赛需现场展示和答辩', official_website: 'http://www.china-cssc.org/', past_papers_url: 'http://www.china-cssc.org/works' },
    { name: '全国大学生天文创新作品竞赛', category: '理学类', description: '天文科学创新作品竞赛', target_audience: '天文学、物理学、空间科学等相关专业全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 3, reg_end_month: 8, requirements: '每队1-5人\n需有1名指导教师\n分为天文观测、天文软件、天文科普等类别\n需提交创新作品和技术报告\n作品须与天文学相关\n决赛需现场展示和答辩' },
    { name: '全国大学生地质技能竞赛', category: '理学类', description: '地质学基础技能竞赛', target_audience: '地质学、地质工程、资源勘查工程等相关专业全日制本科生', fee: '免费', format: 'team', reg_start_month: 5, reg_end_month: 10, requirements: '每队3-4人\n需有1名指导教师\n分为地质技能综合应用和地质标本鉴定等赛项\n考察野外地质调查和室内分析技能\n需在规定时间内完成地质任务\n需提交地质报告' },
    // 经管类 (7)
    { name: '"学创杯"全国大学生创业综合模拟大赛', category: '经管类', description: '创业综合模拟经营竞赛', target_audience: '全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 3, reg_end_month: 6, requirements: '每队3-5人\n需有1名指导教师\n使用创业模拟经营软件进行比赛\n考察市场分析、财务管理、运营决策等能力\n分为初赛（线上模拟）和决赛（现场对抗）\n需提交创业分析报告' },
    { name: '全国大学生财会大数据应用能力大赛', category: '经管类', description: '财会大数据分析与应用竞赛', target_audience: '会计学、财务管理、审计学等相关专业全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 4, reg_end_month: 8, requirements: '每队3-4人\n需有1名指导教师\n围绕财会大数据分析与应用\n需运用数据分析工具处理财务数据\n需提交数据分析报告\n决赛需现场操作和答辩' },
    { name: '全国高校商业精英挑战赛', category: '经管类', description: '商业策划与运营竞赛', target_audience: '经济学、管理学等相关专业全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 3, reg_end_month: 7, requirements: '每队3-5人\n需有1名指导教师\n分为国际贸易、品牌策划、商业谈判等赛项\n需提交商业策划方案\n决赛需现场展示和答辩\n部分赛项需使用英语' },
    { name: '中国大学生服务外包创新创业大赛', category: '经管类', description: '服务外包领域创新创业竞赛', target_audience: '全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 1, reg_end_month: 6, requirements: '每队不超过5人\n需有1名指导教师\n分为A类（企业命题）和B类（自选课题）\n需提交软件作品或解决方案\n作品须具有创新性和实用价值\n决赛需现场答辩' },
    { name: '全国大学生工业工程与精益管理创新大赛', category: '经管类', description: '工业工程与精益管理创新竞赛', target_audience: '工业工程、管理科学与工程等相关专业全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 3, reg_end_month: 7, requirements: '每队3-5人\n需有1名指导教师\n围绕工业工程与精益管理创新\n需提交创新方案和技术报告\n鼓励结合企业实际问题\n决赛需现场答辩和方案展示' },
    { name: '全国企业竞争模拟大赛', category: '经管类', description: '企业经营管理模拟竞赛', target_audience: '经济管理类相关专业全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 4, reg_end_month: 8, requirements: '每队4-5人\n需有1名指导教师\n使用企业经营模拟软件进行对抗\n考察战略规划、市场营销、生产运营、财务管理等综合能力\n分为多轮模拟经营\n需提交经营分析报告' },
    { name: '全国大学生会计信息化技能大赛', category: '经管类', description: '会计信息化技能竞赛', target_audience: '会计学、财务管理等相关专业全日制本科生', fee: '免费', format: 'individual', reg_start_month: 5, reg_end_month: 9, requirements: '个人赛，独立完成\n考察会计信息化操作技能\n需熟练使用财务软件\n比赛内容包括账务处理、报表编制等\n需在规定时间内完成会计业务操作\n考察会计准则和信息化应用能力' },
    // 艺术类 (7)
    { name: '全国大学生广告艺术大赛', category: '艺术类', description: '广告创意设计竞赛', target_audience: '全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 3, reg_end_month: 6, requirements: '每队1-5人\n需有1名指导教师\n围绕年度命题进行广告创意设计\n分为平面类、视频类、动画类、互动类等赛道\n需提交作品电子文件和创意说明\n作品须为原创，不得抄袭' },
    { name: '全国大学生工业设计大赛', category: '艺术类', description: '工业产品设计创新竞赛', target_audience: '工业设计、产品设计等相关专业全日制本科生及研究生', fee: '免费', format: 'individual', reg_start_month: 5, reg_end_month: 9, requirements: '个人赛或团队赛（不超过3人）\n需有1名指导教师\n作品须为工业产品设计\n需提交设计效果图、三视图和设计说明\n作品须具有创新性、实用性和美观性\n鼓励关注社会问题和可持续发展' },
    { name: '全国大学生艺术展演活动', category: '艺术类', description: '大学生艺术作品展演竞赛', target_audience: '全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 1, reg_end_month: 4, requirements: '分为艺术表演类、艺术作品类、艺术实践工作坊等\n表演类每个节目不超过15人\n需有1名指导教师\n作品须体现思想性和艺术性\n表演类节目时长有限制\n需提交作品或节目视频' },
    { name: '全国高校数字艺术设计大赛', category: '艺术类', description: '数字艺术与设计创新竞赛', target_audience: '全日制本科生及研究生', fee: '免费', format: 'individual', reg_start_month: 3, reg_end_month: 7, requirements: '个人赛或团队赛（不超过3人）\n需有1名指导教师\n分为视觉传达、数字影像、交互设计、环境设计等类别\n需提交数字作品文件和设计说明\n作品须为原创数字艺术设计\n需注明使用的设计软件和工具' },
    { name: '中国好创意暨全国数字艺术设计大赛', category: '艺术类', description: '数字艺术创意设计竞赛', target_audience: '全日制本科生及研究生', fee: '免费', format: 'individual', reg_start_month: 4, reg_end_month: 8, requirements: '个人赛或团队赛（不超过5人）\n需有1名指导教师\n分为视觉传达、数字影像、动画设计、交互设计等类别\n需提交作品电子文件和创意说明\n作品须为原创\n鼓励运用新技术和新媒体' },
    { name: '米兰设计周-中国高校设计学科师生优秀作品展', category: '艺术类', description: '设计学科优秀作品国际展示', target_audience: '设计学、美术学等相关专业全日制本科生及研究生', fee: '免费', format: 'individual', reg_start_month: 1, reg_end_month: 3, requirements: '个人赛或团队赛\n需有1名指导教师推荐\n作品须为设计学科相关的优秀作品\n需提交作品高清图片和设计说明（中英文）\n入选作品将在米兰设计周期间展出\n作品须具有国际视野和创新性' },
    { name: '全国大学生环境设计学年奖', category: '艺术类', description: '环境设计专业学年优秀作品评选', target_audience: '环境设计、室内设计、景观设计等相关专业全日制本科生及研究生', fee: '免费', format: 'individual', reg_start_month: 6, reg_end_month: 9, requirements: '个人赛或团队赛（不超过3人）\n需有1名指导教师\n作品须为环境设计相关的学年作品\n需提交设计图纸、效果图和设计说明\n作品须体现设计创新和专业水平\n分为室内设计和景观设计两大类' },
    // 语言类 (6)
    { name: '全国大学生英语竞赛', category: '语言类', description: '大学生英语综合能力竞赛', target_audience: '全日制本科生及研究生（分A、B、C、D四个类别）', fee: '免费', format: 'individual', reg_start_month: 1, reg_end_month: 3, requirements: '个人赛，独立完成\n分为A类（研究生）、B类（英语专业本科生）、C类（非英语专业本科生）、D类（体艺类本科生）\n初赛为笔试，含听力、阅读、写作等\n决赛增加口语测试\n考试时间约120分钟', official_website: 'http://www.chinaneccs.cn/', past_papers_url: 'http://www.chinaneccs.cn/list.php?fid=18' },
    { name: '"外研社·国才杯""理解当代中国"全国大学生外语能力大赛', category: '语言类', description: '外语综合能力竞赛', target_audience: '全日制本科生及研究生', fee: '免费', format: 'individual', reg_start_month: 9, reg_end_month: 12, requirements: '个人赛，独立完成\n分为英语组和多语种组\n英语组设写作、阅读、演讲等赛项\n需围绕"理解当代中国"主题\n初赛在各校举行，复赛和决赛为全国赛\n考察外语综合运用能力和跨文化素养', official_website: 'https://uchallenge.unipus.cn/', past_papers_url: 'https://uchallenge.unipus.cn/2023/works/' },
    { name: '中国日报社"21世纪杯"全国英语演讲比赛', category: '语言类', description: '英语演讲能力竞赛', target_audience: '全日制本科生及研究生', fee: '免费', format: 'individual', reg_start_month: 9, reg_end_month: 12, requirements: '个人赛，独立完成\n分为定题演讲、即兴演讲和问答环节\n定题演讲时间3分钟\n即兴演讲准备时间有限\n考察英语口语表达、逻辑思维和临场应变能力\n各校选拔后参加省赛和全国赛', official_website: 'https://contest.i21st.cn/', past_papers_url: 'https://contest.i21st.cn/article/index.html' },
    { name: '"批改网杯"全国大学生英语写作大赛', category: '语言类', description: '英语写作能力竞赛', target_audience: '全日制本科生（含高职）', fee: '免费', format: 'individual', reg_start_month: 9, reg_end_month: 11, requirements: '个人赛，独立完成\n通过批改网在线平台提交作品\n需在规定时间内完成英语作文\n考察英语写作能力和语言表达水平\n分为初赛和决赛\n作品由系统评分和专家评审结合', official_website: 'http://www.pigai.org/', past_papers_url: 'http://www.pigai.org/index.php?c=contest&a=list' },
    { name: '全国大学生日语翻译大赛', category: '语言类', description: '日语翻译能力竞赛', target_audience: '日语专业及日语相关方向全日制本科生及研究生', fee: '免费', format: 'individual', reg_start_month: 4, reg_end_month: 7, requirements: '个人赛，独立完成\n分为笔译赛和口译赛\n笔译赛需完成日中互译\n口译赛考察即时翻译能力\n需具备日语N2及以上水平\n考察翻译准确性和语言表达能力' },
    { name: '全国高校学生跨文化能力大赛', category: '语言类', description: '跨文化交际能力竞赛', target_audience: '全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 5, reg_end_month: 10, requirements: '每队2-4人\n需有1名指导教师\n围绕跨文化交际主题\n分为案例分析和情景展示环节\n需展示跨文化沟通和问题解决能力\n决赛需现场展示和答辩' },
    // 医学类 (5)
    { name: '全国大学生基础医学创新研究暨实验设计论坛', category: '医学类', description: '基础医学创新研究竞赛', target_audience: '基础医学、临床医学、药学等相关专业全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 3, reg_end_month: 7, requirements: '每队3-5人\n需有1-2名指导教师\n分为基础医学实验设计和创新研究两个赛道\n需提交实验设计方案或研究论文\n实验设计须具有科学性和创新性\n决赛需现场答辩和实验展示' },
    { name: '全国大学生临床技能竞赛', category: '医学类', description: '临床医学技能竞赛', target_audience: '临床医学专业全日制本科生（通常为三年级及以上）', fee: '免费', format: 'team', reg_start_month: 1, reg_end_month: 4, requirements: '每队5人\n需有2-3名指导教师\n以学校为单位参赛\n考察病史采集、体格检查、辅助检查判读、临床操作等技能\n使用标准化病人和模拟设备\n比赛分为站点式考核' },
    { name: '全国大学生药学/中药学实验技能竞赛', category: '医学类', description: '药学实验技能竞赛', target_audience: '药学、中药学、药物制剂等相关专业全日制本科生', fee: '免费', format: 'individual', reg_start_month: 3, reg_end_month: 7, requirements: '个人赛，独立完成\n分为药学组和中药学组\n考察药物分析、药物化学、药剂学等实验技能\n需在规定时间内完成实验操作\n评分包括操作规范性、结果准确性等\n需遵守实验室安全规范' },
    { name: '全国大学生公共卫生综合知识与技能大赛', category: '医学类', description: '公共卫生知识与技能竞赛', target_audience: '预防医学、公共卫生等相关专业全日制本科生', fee: '免费', format: 'team', reg_start_month: 4, reg_end_month: 8, requirements: '每队4-5人\n需有1-2名指导教师\n以学校为单位参赛\n考察流行病学、卫生统计学、环境卫生等知识\n分为理论知识竞答和技能操作两部分\n技能操作包括现场调查和数据分析' },
    { name: '全国大学生护理学本科临床技能大赛', category: '医学类', description: '护理学临床技能竞赛', target_audience: '护理学专业全日制本科生', fee: '免费', format: 'team', reg_start_month: 3, reg_end_month: 6, requirements: '每队4人\n需有1-2名指导教师\n以学校为单位参赛\n考察基础护理、专科护理等临床技能\n使用模拟病人和标准化病人\n分为个人赛和团体赛\n需展示护理操作和沟通能力' },
    // 机器人类 (6)
    { name: '中国机器人大赛暨RoboCup机器人世界杯中国赛', category: '机器人类', description: '机器人技术综合竞赛', target_audience: '全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 3, reg_end_month: 7, requirements: '每队3-10人（视项目而定）\n需有1-2名指导教师\n分为RoboCup足球、救援、家庭服务等多个项目\n需自主设计和编程机器人\n机器人须满足各项目的尺寸和重量限制\n需提交技术报告', official_website: 'http://www.robocup.org.cn/', past_papers_url: 'http://www.robocup.org.cn/works' },
    { name: '全国大学生机器人大赛-RoboMaster', category: '机器人类', description: '机器人对抗竞赛', target_audience: '全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 1, reg_end_month: 8, requirements: '以学校为单位组队，每队最多35人\n需有指导教师\n需设计制作多台步兵、英雄、工程等机器人\n机器人须满足尺寸、重量和功率限制\n比赛为机器人对抗赛\n需提交技术报告和答辩', official_website: 'https://www.robomaster.com/', past_papers_url: 'https://www.robomaster.com/zh-CN/resource/pages/1035' },
    { name: '全国大学生机器人大赛-RoboCon', category: '机器人类', description: '机器人设计与制作竞赛', target_audience: '全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 1, reg_end_month: 6, requirements: '以学校为单位组队，每队不超过15人\n需有1-2名指导教师\n每年比赛主题不同\n需根据年度主题设计制作机器人\n机器人须在规定场地完成指定任务\n需提交技术方案和视频', official_website: 'http://www.robocon.cn/', past_papers_url: 'http://www.robocon.cn/works' },
    { name: '国际水中机器人大赛', category: '机器人类', description: '水中机器人技术竞赛', target_audience: '全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 4, reg_end_month: 8, requirements: '每队2-6人\n需有1名指导教师\n需设计制作水中机器人\n分为水中搜救、水中对抗、水中表演等项目\n机器人须能在水中自主运动\n需提交技术报告和设计文档' },
    { name: '中国高校智能机器人创意大赛', category: '机器人类', description: '智能机器人创意设计竞赛', target_audience: '全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 3, reg_end_month: 9, requirements: '每队2-5人\n需有1名指导教师\n围绕智能机器人创意设计\n需提交创意方案和技术报告\n鼓励人工智能技术的创新应用\n决赛需现场演示和答辩' },
    { name: '全国大学生无人机相关竞赛', category: '机器人类', description: '无人机技术应用竞赛', target_audience: '全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 4, reg_end_month: 10, requirements: '每队2-5人\n需有1名指导教师\n分为无人机设计、编程飞行、航拍应用等赛项\n需自主设计或编程控制无人机\n须遵守无人机飞行安全规范\n需提交技术报告和飞行视频' },
    // 职业技能类 (5)
    { name: '全国职业院校技能大赛', category: '职业技能类', description: '职业技能综合竞赛', target_audience: '全日制高职高专在校学生', fee: '免费', format: 'team', reg_start_month: 1, reg_end_month: 5, requirements: '以学校为单位组队，每队2-4人（视赛项而定）\n需有1-2名指导教师\n分为装备制造、电子信息、交通运输等多个大类\n考察职业技能操作水平\n需在规定时间内完成技能操作任务\n评分注重操作规范性和完成质量' },
    { name: '全国大学生测绘学科创新创业智能大赛', category: '职业技能类', description: '测绘技术创新竞赛', target_audience: '测绘工程、遥感科学与技术、地理信息科学等相关专业全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 3, reg_end_month: 7, requirements: '每队3-5人\n需有1名指导教师\n分为测绘技能、虚拟仿真、创新创业等赛道\n需完成测量、数据处理和成果编制\n需提交技术报告和成果文件\n决赛需现场操作和答辩' },
    { name: '全国大学生物流设计大赛', category: '职业技能类', description: '物流系统设计与优化竞赛', target_audience: '物流管理、物流工程、供应链管理等相关专业全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 3, reg_end_month: 7, requirements: '每队4-6人\n需有1-2名指导教师\n围绕企业实际物流问题进行方案设计\n需提交物流系统设计方案和分析报告\n方案须具有可行性和创新性\n决赛需现场答辩' },
    { name: '全国大学生BIM毕业设计创新大赛', category: '职业技能类', description: 'BIM技术应用与创新竞赛', target_audience: '土木工程、建筑学、工程管理等相关专业全日制本科生', fee: '免费', format: 'team', reg_start_month: 1, reg_end_month: 5, requirements: '每队3-5人\n需有1-2名指导教师\n需运用BIM技术完成建筑工程设计\n需提交BIM模型和设计文档\n分为建筑设计、结构设计、施工管理等赛道\n需展示BIM技术的综合应用能力' },
    { name: '全国大学生智能建造与管理创新竞赛', category: '职业技能类', description: '智能建造技术创新竞赛', target_audience: '土木工程、智能建造、工程管理等相关专业全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 4, reg_end_month: 8, requirements: '每队3-5人\n需有1名指导教师\n围绕智能建造技术创新\n需提交创新方案和技术报告\n鼓励运用BIM、物联网、人工智能等技术\n决赛需现场答辩和方案展示' },
    // 农学类 (3)
    { name: '全国大学生生命科学创新创业大赛', category: '农学类', description: '生命科学领域创新创业竞赛', target_audience: '生物科学、生物技术、农学等相关专业全日制本科生及研究生', fee: '免费', format: 'team', reg_start_month: 3, reg_end_month: 7, requirements: '每队3-5人\n需有1-2名指导教师\n分为创新实验和创业计划两个赛道\n创新实验需提交研究成果和论文\n创业计划需提交商业计划书\n决赛需现场答辩和成果展示' },
    { name: '全国大学生动物科学专业技能大赛', category: '农学类', description: '动物科学专业技能竞赛', target_audience: '动物科学、动物医学、畜牧兽医等相关专业全日制本科生', fee: '免费', format: 'team', reg_start_month: 4, reg_end_month: 8, requirements: '每队4-5人\n需有1-2名指导教师\n以学校为单位参赛\n考察动物解剖、饲料分析、繁殖技术等专业技能\n分为理论知识和实践操作两部分\n需在规定时间内完成技能操作' },
    { name: '全国大学生植物保护专业能力大赛', category: '农学类', description: '植物保护专业能力竞赛', target_audience: '植物保护、农学、园艺等相关专业全日制本科生', fee: '免费', format: 'team', reg_start_month: 5, reg_end_month: 9, requirements: '每队3-5人\n需有1名指导教师\n以学校为单位参赛\n考察病虫害识别、农药配制、植保方案设计等技能\n分为理论知识竞答和实践操作\n需在规定时间内完成植保任务' },
];
export function seedCompetitions(db: DatabaseWrapper): void {
    const insert = db.prepare(`
    INSERT INTO competitions (name, category, description, target_audience, fee, format, reg_start_month, reg_end_month, requirements, official_website, past_papers_url)
    VALUES (@name, @category, @description, @target_audience, @fee, @format, @reg_start_month, @reg_end_month, @requirements, @official_website, @past_papers_url)
  `);
    const insertMany = db.transaction((items) => {
        for (const item of items) {
            insert.run({
                ...item,
                official_website: item.official_website || null,
                past_papers_url: item.past_papers_url || null,
            });
        }
    });
    insertMany(competitions);
}